### ISSUE TITLE
Searching indication in the popup

### ISSUE THREAD

**Issue by shilomagen** [shilomagen/passport-extension#4]
At the moment, there is no way to know if the extension is searching for appointment or you need to authenticate again.
In order to make it happen we need to do the following:

1. Persist the bot status in local storage
2. Update the status by request
3. Render status in popup

**Comment by shilomagen** [comment]
Done

**Comment by kohend** [comment]
It doesn't seem fixed, it showed that it's disconnected despite finding me a spot. (16th Apr version from the store)
